# Top-level JSON keys
STUDENTS = "alumnos"
TEACHERS = "profesores"
COURSES = "cursos"
COURSE_INSTANCES = "instancias"
SECTIONS = "secciones"
CLASSROOMS = "salas"
GRADES = "notas"
STUDENT_SECTIONS = "alumnos_seccion"
YEAR = "año"
SEMESTER = "semestre"

# Common field keys
ID = "id"
NAME = "nombre"
CAPACITY = "capacidad"
EMAIL = "correo"
ENTRY_YEAR = "anio_ingreso"
CODE = "codigo"
DESCRIPTION = "descripcion"
CREDITS = "creditos"
REQUISITES = "requisitos"
COURSE_ID = "curso_id"
COURSE_INSTANCE = "instancia_curso"
TEACHER_ID = "profesor_id"
INSTANCE = "instancia"
TOPIC_ID = "topico_id"
EVALUATION = "evaluacion"
GRADE = "nota"
STUDENT_ID = "alumno_id"
SECTION_ID = "seccion_id"

# Other constants for utility
MAIN_COURSE_CODE = "main_course_code"
REQUISITE_CODE = "prerequisite_code"

# Evaluation-specific keys
EVALUATION_TYPE = "tipo"
TOPIC_COMBINATIONS = "combinacion_topicos"
TOPICS = "topicos"
TOPIC_WEIGHT = "valor"
TOPIC_COUNT = "cantidad"
TOPIC_TYPE = "tipo"
TOPIC_VALUES = "valores"
TOPIC_MANDATORY = "obligatorias"

# Labels
CLASSROOMS_LABEL = "classrooms"
STUDENTS_LABEL = "students"
TEACHERS_LABEL = "teachers"
COURSES_LABEL = "courses"
REQUISITES_LABEL = "requisites"
COURSE_INSTANCES_LABEL = "course instances"
SECTIONS_LABEL = "sections"
EVALUATIONS_LABEL = "evaluations"
EVALUATION_INSTANCES_LABEL = "evaluation instances"
STUDENT_SECTIONS_LABEL = "student sections"
GRADES_LABEL = "grades"