# Top-level JSON keys
STUDENTS = "alumnos"
TEACHERS = "profesores"
COURSES = "cursos"
INSTANCES = "instancias"
SECTIONS = "secciones"
CLASSROOMS = "salas"
GRADES = "notas"
STUDENT_SECTIONS = "alumnos_seccion"
YEAR = "año"
SEMESTER = "semestre"

# Common field keys
ID = "id"
NAME = "nombre"
CAPACITY = "capacidad"
EMAIL = "correo"
ENTRY_YEAR = "anio_ingreso"
CODE = "codigo"
DESCRIPTION = "descripcion"
CREDITS = "creditos"
PREREQUISITES = "requisitos"
COURSE_ID = "curso_id"
COURSE_INSTANCE = "instancia_curso"
TEACHER_ID = "profesor_id"
INSTANCE = "instancia"
TOPIC_ID = "topico_id"
EVALUATION = "evaluacion"
GRADE = "nota"
STUDENT_ID = "alumno_id"
SECTION_ID = "seccion_id"