from app.models.course import Course
from app.models.course_instance import CourseInstance
from app.models.section import Section
from app.models.user import User
from app.models.requisite import Requisite
from app.models.evaluation import Evaluation
from app.models.evaluation_instance import EvaluationInstance
from app.models.user_section import UserSection
from app.models.user_evaluation_instance import UserEvaluationInstance